language: java
jobs:
  include:
  - stage: test
    script: "./scripts/stage.sh unit-test"
  - stage: publish
    if: branch = master
    script: "./scripts/stage.sh publish-to-bintray"
env:
  global:
    secure: DnQ3b2Z0PGMTIIY+uJ1dgZJaFJ3gbZtqqqAfU008Wys34XM0DZrZBBjIkiedWEMZEbcF5jTW0yTos2Lju20CnWFjMlyU7wVx/Tk8jmGJnb2Gi9zuuH8ZMJfMZK8JRKVp5mJtpqiov53LVTNW6yu/Hgh3FDL8RYZY1hHyeCL6n/WCpQGQPPkYStilmQt9pVCEhOF7erOm2uWpFRT4JYZD2o0pbo/9cH/ArHqZrt+DDSBnpqk6EcLzOqJ3M+6dIS7Xlc/TqnIOCNwEoSYf3euGmtF/rtvgIDF+D5ikCCSZFhpS8ou+G++rV80A0/aX47BFHBmt7yOkZmUORaWRHT5x+HFrFNl7FejCVr0HoSQPIUSIO0CbB1Kut/PvK/vVq4GGmBFeDd0J32OYwxIpDwBCOZ3ix6O+g0aB/rzvjXXJHD3d7m2Ib4cOF43NdO/kMsDjKH/spGSc/sArkMMNXXy4skbhOQSqrh59cBkcTLiPaQzciQNa0JJId4mpOOP8QK7EsJxIugbgYCvAnweq9yv6K2Xn42Ir9govziMXTK19DQ3bqwGi92X13x1wPQMKtrQCqkXx24mxB2P1e/StlGtYdueluuwzd1266W0T7iiyKvncaN+SXtlcNZJJzhgxkWammh2nhdFk8rMbQivEiz3fEnaR62OsxrrTzTGKD9YbgC0=
