language: java
jobs:
  include:
  - stage: test
    script: "./scripts/stage.sh unit-test"
  - stage: publish
    if: branch = master
    script: "./scripts/stage.sh publish-to-bintray"
env:
  matrix:
    secure: bJQOIK7kPYgqXhcKnv8NLxJI1mqxaP3lC+bXyFXprzd6Ta6vb8oZyc9eT1IXBnj70Zrq1q3NBePncFL/G+OG5QGkjDzbReJEBtCEZfhCVhklvWShCnShYimc+YFyxi7pBDAS6Lmf+RKQWK4H7gyFmn9IrUNeABzz0WgYfwpzjwtDuqNRv67tXavYvvzDfBqoc4nkw8chwLm2KSUW8rA/PxnGQ6/Zn0hDmucR3GW+Of882Z+LT6lvoLwoWSNyNw12SGPStDmqvHg76pN5m3CTnnTuNj4FEruel1hUnZBGXGTkPvLRSuSTKcI4xtDXUf/iBSS6NiUiqCGrhBfB2ZPItnKX2bu3NtbnBalkHtQJNytVG70nkji7tAQKJqstRumAH2aaPgeAlIsqmLI4KaCtfYnu1m9dxtpVCH3cdno/H8YMNxojVByTIFdUL/HBPPpT5vvCeJn3fHw9NkqwQ3B1/CuWV0cdADoVjSPlDAtdARNsLn+PX/hAJ9Fbd03Qoz9ayx7yv97SkOYswAYL/ShnHOy8rg7vsyFP6glKiF23J7lrqumxLgIbo6w//0g/YmZEndq3WTALWI5sV04kBQLE2dGLQllgmdz/ClJwb6pRvORkcFqgMFAucGN+bhf7CbdSJA2gdvf6s1Pg19k93uu+VWbAQe6+HWCxmr/SAzqLMXQ=
