language: java
jobs:
  include:
  - stage: test
    script: "./scripts/stage.sh unit-test"
  - stage: publish
    if: branch = master
    script: "./scripts/stage.sh publish-to-bintray"
env:
  matrix:
    secure: HRZW8npa9RHRgdrxVFHDNYFphdr4ZJKTB0SZF6dVrcUGsHWyQo56E141qvwEgXN5wOhXmRG3/JSIc8soxdAUi7kjVO5HVDm3cirQHtzipqDqWA5DW69mu40If2qH5pK7L2UudxoCI3UOiq95dXA+EaNH57PWEDS6jgEcwNYq6BTBPHsBbdYqeP/uvvN/yOyF0knWQuGblU9tiT/dD205lYMaAuCnjvmNc5wbhlgxts7OJLUm2m/Xlp2PlwMypxb8KDa/+S9qgCh+3wja+offzlEp2c+VrMTixlW9qWWVPsC3UogBmRcpSLN4tkpbc/p4D5nycLPxzSMS6daTmrVrF7WnZKQ/oD3KCHX95IOLmztOewJEuUAfczkd4X6fmWIOPun0dT7MvwB4oCd1roWx93g1RLcLMf/yWdTf9bojCzVjuzECBuKZpQTMmTUAYia+Ab1hEInr7PIq03BuUSZs3QvIT3eoveMeroQYe27o3bET0hIqZ0GqBcgbnbDPOsK2HkGk+AV52GgmQI7q3cynn5CyWv/+fo+i+o88mN3ASz46XCNdfxV+pWyF5Vy/tGRFkTw9NmKBuQyS/FzsCfb418PHbgf8wMf7mX0YeAufrULMjvuAX3qiGmMOz0xpXL6E3zxr80yLdTEnHPpqhowmewJswKTbhnY8OG3TyltNGRY=
