plugins {
  id 'com.github.spotbugs' version '6.0.26' apply false
  id 'checkstyle'
  id 'org.owasp.dependencycheck' version '11.1.0'
  id 'com.github.kt3k.coveralls' version '2.12.2'
  id 'com.vanniktech.maven.publish' version '0.30.0'
}

apply plugin: 'org.owasp.dependencycheck'

repositories {
  mavenLocal()
  maven {
    url = "https://repo.maven.apache.org/maven2"
  }
  maven {
    url = "https://repo1.maven.org/maven2"
  }
}

tasks.withType(Copy).all {
  duplicatesStrategy 'exclude'
}

dependencyCheck {
  nvd.apiKey = System.getenv("NVD_API_KEY")
  nvd.datafeedUrl = "https://mirror.cveb.in/nvd/json/cve/1.1/nvdcve-1.1-{0}.json.gz"
}

apply from: 'gradle/java.gradle'
